controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [motoman_joint_s, motoman_joint_l, motoman_joint_e, motoman_joint_u, motoman_joint_r, motoman_joint_b, motoman_joint_t]
